{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMTJtA7i2LqQ56IH0ARc39s",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/usmangul23/Scientific-Calculator/blob/main/app_py_V2.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "import streamlit as st\n",
        "import math\n",
        "\n",
        "# Calculator functions\n",
        "def add(x, y):\n",
        "    return x + y\n",
        "\n",
        "def subtract(x, y):\n",
        "    return x - y\n",
        "\n",
        "def multiply(x, y):\n",
        "    return x * y\n",
        "\n",
        "def divide(x, y):\n",
        "    if y == 0:\n",
        "        return \"Error! Division by zero.\"\n",
        "    return x / y\n",
        "\n",
        "def square_root(x):\n",
        "    return math.sqrt(x)\n",
        "\n",
        "def power(x, y):\n",
        "    return math.pow(x, y)\n",
        "\n",
        "def logarithm(x):\n",
        "    if x > 0:\n",
        "        return math.log10(x)\n",
        "    return \"Error! Logarithm undefined for non-positive values.\"\n",
        "\n",
        "def sine(x):\n",
        "    return math.sin(math.radians(x))\n",
        "\n",
        "def cosine(x):\n",
        "    return math.cos(math.radians(x))\n",
        "\n",
        "def tangent(x):\n",
        "    return math.tan(math.radians(x))\n",
        "\n",
        "def factorial(x):\n",
        "    if x < 0:\n",
        "        return \"Error! Factorial undefined for negative numbers.\"\n",
        "    return math.factorial(x)\n",
        "\n",
        "# Streamlit app\n",
        "st.title(\"Scientific Calculator\")\n",
        "\n",
        "# Input from user\n",
        "operation = st.selectbox(\"Select an operation\",\n",
        "                         [\"Add\", \"Subtract\", \"Multiply\", \"Divide\", \"Square Root\",\n",
        "                          \"Exponentiation (x^y)\", \"Logarithm\", \"Sine\", \"Cosine\",\n",
        "                          \"Tangent\", \"Factorial\"])\n",
        "\n",
        "if operation in [\"Add\", \"Subtract\", \"Multiply\", \"Divide\", \"Exponentiation (x^y)\"]:\n",
        "    num1 = st.number_input(\"Enter first number\", value=0.0)\n",
        "    num2 = st.number_input(\"Enter second number\", value=0.0)\n",
        "else:\n",
        "    num1 = st.number_input(\"Enter the number\", value=0.0)\n",
        "\n",
        "# Perform calculation\n",
        "if st.button(\"Calculate\"):\n",
        "    if operation == \"Add\":\n",
        "        result = add(num1, num2)\n",
        "    elif operation == \"Subtract\":\n",
        "        result = subtract(num1, num2)\n",
        "    elif operation == \"Multiply\":\n",
        "        result = multiply(num1, num2)\n",
        "    elif operation == \"Divide\":\n",
        "        result = divide(num1, num2)\n",
        "    elif operation == \"Square Root\":\n",
        "        result = square_root(num1)\n",
        "    elif operation == \"Exponentiation (x^y)\":\n",
        "        result = power(num1, num2)\n",
        "    elif operation == \"Logarithm\":\n",
        "        result = logarithm(num1)\n",
        "    elif operation == \"Sine\":\n",
        "        result = sine(num1)\n",
        "    elif operation == \"Cosine\":\n",
        "        result = cosine(num1)\n",
        "    elif operation == \"Tangent\":\n",
        "        result = tangent(num1)\n",
        "    elif operation == \"Factorial\":\n",
        "        result = factorial(int(num1))\n",
        "\n",
        "    st.write(f\"The result is: {result}\")\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "h7uBk7XoI7UA",
        "outputId": "d540f150-02a4-4f8d-c2bc-c6857f518931"
      },
      "execution_count": 8,
      "outputs": [
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "\n",
            "Select Operation:\n",
            "1. Addition\n",
            "2. Subtraction\n",
            "3. Multiplication\n",
            "4. Division\n",
            "5. Square Root\n",
            "6. Exponentiation (x^y)\n",
            "7. Logarithm (base 10)\n",
            "8. Sine (degrees)\n",
            "9. Cosine (degrees)\n",
            "10. Tangent (degrees)\n",
            "11. Factorial\n",
            "\n",
            "Enter choice (1-11): 3\n",
            "\n",
            "Enter first number: 4\n",
            "Enter second number: 6\n",
            "Result: 24.0\n",
            "\n",
            "Do you want to perform another calculation? (yes/no): yes\n",
            "\n",
            "Select Operation:\n",
            "1. Addition\n",
            "2. Subtraction\n",
            "3. Multiplication\n",
            "4. Division\n",
            "5. Square Root\n",
            "6. Exponentiation (x^y)\n",
            "7. Logarithm (base 10)\n",
            "8. Sine (degrees)\n",
            "9. Cosine (degrees)\n",
            "10. Tangent (degrees)\n",
            "11. Factorial\n",
            "\n",
            "Enter choice (1-11): 4\n",
            "\n",
            "Enter first number: 4\n",
            "Enter second number: 0\n",
            "Result: Error! Division by zero.\n",
            "\n",
            "Do you want to perform another calculation? (yes/no): no\n"
          ]
        }
      ]
    }
  ]
}